### ISSUE TITLE
Replace `rusb` (libusb bindings) with native Rust

### ISSUE THREAD

**Issue by hardBSDk** [tuna-f1sh/cyme#17]

**Comment by tuna-f1sh** [comment]
Not personally but [nusb](https://github.com/kevinmehall/nusb) is on my radar. It would be a pure Rust solution rather than libusb but not explored whether porting would be possible yet. Open to contributions if you're interested in exploring.

**Comment by tuna-f1sh** [comment]
@hardBSDk if you interested in testing this, the PR #26 can be built with pure Rust using `--no-default-features -F=native`.

**Comment by hardBSDk** [comment]
@tuna-f1sh It works but don't show the xHCI ports.

**Comment by tuna-f1sh** [comment]
Yes this was actually a change I made because by default nusb does not list xHCI (root_hubs). It made me re-think the default list and not to show them. The lsusb mode will though (since it does): `cargo run --no-default-features -F=native -- --lsusb`. 

Do you think they are useful in the list output? I figured not since they are not something one does anything with. They are presented in `--tree` to show which root_hub devices are attached - I think this is useful.
