### ISSUE TITLE
[Feature Request] Add kernel module used for the device

### ISSUE THREAD

**Issue by dzervas** [tuna-f1sh/cyme#41]
Thank you for the amazing tool!

The only thing missing for me is the kernel module used, something that `usb-devices -k` shows in a very ugly way

**Comment by tuna-f1sh** [comment]
Thanks. Yes this would be quite nice and should be quite simple with sysfs I think. I’ll have a look.

**Comment by tuna-f1sh** [comment]
I actually forgot that the driver block will show this at device and interface level. It's not a default display block so probably why you missed it. You can actually customise the display blocks to show it with current release. For example:

```
❯ cyme --blocks vendor-id --blocks product-id --blocks name --blocks serial  --blocks driver --interface-blocks uid-class --interface-blocks driver -vv --tree --headings
```

Shows usb and the gs_usb interface:

<img width="552" alt="Screenshot 2024-10-14 at 15 13 06" src="https://github.com/user-attachments/assets/10d54d8c-274a-4cac-aa80-6670bedc9122">

Since this information is useful but only on Linux, I've made a change so the driver is a default display block on Linux and will add to next release.

**Comment by tuna-f1sh** [comment]
New defaults on Linux will show:

<img width="853" alt="Screenshot 2024-10-14 at 15 14 58" src="https://github.com/user-attachments/assets/99bd1400-1c98-4c60-ac57-8735cf7ac8ec">

**Comment by dzervas** [comment]
awesome! thank you!
